name: Continuous Deployment

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      -
        name: Create release
        id: release-please
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: python